### ISSUE TITLE
[KKS] KKS_StudioImageEmbed and KKS_MaterialEditor conflict?

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/KK_Plugins#106]
Environment
BepInEx 5.4.16 x64 + BepisPlugins r16.8.1 + Illusion Modding API v1.26
and
KKS_MaterialEditor v3.1.8 + KKS_StudioImageEmbed v1.0.1

In KKS_CharaStudio, the scene will not finish loading.
It will finish if only one of MaterialEditor or StudioImageEmbed is used.

**Comment by DeathWeasel1337** [comment]
This should be fixed now if you have the latest release of both plugins
