### ISSUE TITLE
[KKS] KKSABMX can't support height changes due to "character changes" in KKS_CharaStudio.

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/KK_Plugins#107]
For existing scene file,
The height scale is not applied to characters placed when "Character Change" is performed using a character card with a height scale other than 100.
In the case of "New Load", the height will be changed after loading.

**Comment by leoftm** [comment]
If you use "add→character→change character" to replace an existing character, the overlay and MaterialEditor settings don't seem to be reflected, so this may not be an ABMX-specific problem.
If you use "add→character→load", the material is also applied.

**Comment by DeathWeasel1337** [comment]
Replacing characters in a scene seems to work fine for me, ABMX and MaterialEditor changes are applied correctly. Make sure all your plugins are up to date and if this is still an issue let me know, and attach your output_log.txt
