### ISSUE TITLE
[KKS]KK_Plugins Subtitles BUG

### ISSUE THREAD

**Issue by fldx** [IllusionMods/KK_Plugins#115]
对话时有概率触发BUG
![QQ截图20211105021213](https://user-images.githubusercontent.com/11643460/140396142-d607e212-0974-4baf-86e5-83b9518c1b5e.png)

**Comment by jarbean** [comment]
are you sure you BepInEx is 5.3 not BepInEx5.4.17
kk_plugin is base on BepInEx5.3
你的BepInEx肯定是5.4你要降级5.3才能用。
screw this noise的kks R2是基于5.4所以对话会卡住。
但去马赛克又是基于5.4，想要对话就是降级5.3，想解码就5.4。
stn整合的包缺少info_50.unity3d这个文件莫名其妙的多了个info_60.unity3d，
stn这家伙老丢三落四

**Comment by jarbean** [comment]
KK_Plugins now can suport BepInEx5.4？
I really want to know。
cause most kks‘s plugin is base on BepInEx5.4

**Comment by fldx** [comment]
BepInEx 5.4.16.0

**Comment by jarbean** [comment]
缺info_50.unity3d这个你的包有这个吗？没的话可能出问题，我怀疑他压缩游戏时整没了，也可能那家伙把info_50.unity3d改成info_60.unity3d，没这个部分对话也可能找不到object.
abdata\communication\info_50.unity3d这个缺失了

**Comment by jarbean** [comment]
BepInEx_x64_5.4.15.0才是最匹配的。LogOutput上面写了

**Comment by fldx** [comment]
这个是正常
![image](https://user-images.githubusercontent.com/11643460/140869788-f3883224-7747-4faa-b4cc-51b8110cb4aa.png)
下面是不正常的
![image](https://user-images.githubusercontent.com/11643460/140870032-c05f1f94-4dd0-429f-bbcf-21343b5c6b5d.png)
如果是文件资源问题,我就把这个issues关闭了
