### ISSUE TITLE
Animation Overdrive is not working

### ISSUE THREAD

**Issue by LifeloverIXXI** [IllusionMods/KK_Plugins#120]
installed flashbangZ koikatu, after installed manlymarco HF patch
animation overdrive still not working after 5 time reinstall, idk what to do.
Maybe this happened because i have installed KPlug too.

**Comment by DeathWeasel1337** [comment]
I can't really provide tech support for games with kplug installed since it's closed source and I don't have it myself. If you have trouble, your best bet is to ask in the help channel of the Koikatsu Discord.
