### ISSUE TITLE
setup.xml corrupted 

### ISSUE THREAD

**Issue by tyusaa** [IllusionMods/KK_Plugins#121]
my koikatsu files, setup.xml corrupted in user data folder please give me solution, i dont understand about mod in folder game

**Comment by IDontHaveIdea** [comment]
If you still have this problem UserData/setup.xml can be edited and fixed in any editor.  You can delete the file an run InitSetting.exe and it will recreated with the default values.  Make any changes in the configuration you need and launch the game.
