### ISSUE TITLE
 KK_PoseTools.v1.1 makes everything in the plugin list disappear in studio

### ISSUE THREAD

**Issue by Bar2co** [IllusionMods/KK_Plugins#124]
![Desktop Screenshot 2022 02 20 - 21 14 27 67](https://user-images.githubusercontent.com/47928416/154863347-dd0915e0-3ebc-479c-95a9-0cb1636e2639.png)

**Comment by DeathWeasel1337** [comment]
Very strange, it works properly on my end. Could it be that you didn't install the latest BepisPlugins? If you upload your output_log.txt I can try to see what the error is.

**Comment by Bar2co** [comment]
Here you go.

[output_log.txt](https://github.com/IllusionMods/KK_Plugins/files/8126011/output_log.txt)

**Comment by Bar2co** [comment]
Someon told me to update bepinex ad no bepisplugins. It works now

**Comment by DeathWeasel1337** [comment]
Glad you got it worked out
