### ISSUE TITLE
[KKS][UncensorSelector] Can't give balls to females

### ISSUE THREAD

**Issue by ManlyMarco** [IllusionMods/KK_Plugins#148]
Maker dropdown has no effect.

**Comment by DeathWeasel1337** [comment]
Works on my box. Balls cannot be added without also adding a penis, this is true of regular Koikatsu and males as well.

**Comment by ManlyMarco** [comment]
Definitely doesn't work. KKS with EX installed, tested with and without BP, nothing in log. Load straight to female maker, go to body tab, select a penis, select some balls, no balls appear.

**Comment by ManlyMarco** [comment]
Issue traced down to KKS_UncensorSelector_Base.zipmod missing, needs a modpack change.

**Comment by DDLshxyx** [comment]
still having the same problems now
