### ISSUE TITLE
[HS2] VR unplayable using HS_MaterialEditor > 3.1.9

### ISSUE THREAD

**Issue by FaySmash** [IllusionMods/KK_Plugins#149]
Using the newest MaterialEditor Release:
![newest Material Editor](https://user-images.githubusercontent.com/30392780/173185312-40de0b83-79bd-461d-b308-45da5c90736f.png)
[output_log.txt](https://github.com/IllusionMods/KK_Plugins/files/8883720/output_log.txt)

Using the 3.1.9 MaterialEditor Release:
![3 1 9 Material Editor](https://user-images.githubusercontent.com/30392780/173185417-ed84672f-8394-4f23-93b8-cc6f7ad44c33.png)
[output_log.txt](https://github.com/IllusionMods/KK_Plugins/files/8883724/output_log.txt)

I ruled every other mod out as the case, other people have experienced this as well. The problem only appear during H-scenes, not in the title screen.

**Comment by ManlyMarco** [comment]
Can you show the FPSCounter output or does it not show up in VR? On which version exactly did this start happening?

**Comment by FaySmash** [comment]
Thanks for getting back at me
> Can you show the FPSCounter output or does it not show up in VR?
You can see it after the D3D11 Label, 10 and 55 (capped) fps
> On which version exactly did this start happening?
like the title says, all versions greater than 1.3.9 (haven't tested the latest release thought I suspect the issue still stands)

**Comment by ManlyMarco** [comment]
> You can see it in the screenshots after the D3D11 Label, 10 and 55 (capped) fps

FPSCounter gives much more information that I need, specifically times spent in different sections. Overall FPS doesn't really help.

**Comment by ManlyMarco** [comment]
[HS2_MaterialEditor_debug.zip](https://github.com/IllusionMods/KK_Plugins/files/9995396/HS2_MaterialEditor_debug.zip)
Can you try this build? Trigger the issue and send the resulting output_log here or on discord. Assuming this is something that started happening in 3.1.10, this should at least give a good idea about what is happening.

**Comment by FaySmash** [comment]
> [HS2_MaterialEditor_debug.zip](https://github.com/IllusionMods/KK_Plugins/files/9995396/HS2_MaterialEditor_debug.zip) Can you try this build? Trigger the issue and send the resulting output_log here or on discord. Assuming this is something that started happening in 3.1.10, this should at least give a good idea about what is happening.

Sorry for the delay but here you go!
FPS Counter:
![fps](https://user-images.githubusercontent.com/30392780/201544510-4d930bad-e30e-455d-b721-8ca94732f993.png)

Log:
[output_log.txt](https://github.com/IllusionMods/KK_Plugins/files/9998202/output_log.txt)

---

For reference, FPS Counter with 1.3.9:
![fps](https://user-images.githubusercontent.com/30392780/201544636-64e7f841-c0cd-48fd-bf29-5924a20f2ebb.png)

**Comment by FaySmash** [comment]
Here ya go! I doubt that this information is helpful enough tho 😬

![Unbenannt](https://user-images.githubusercontent.com/30392780/201779777-ec566a92-3042-49dd-8ba1-eb6d9615887c.png)

**Comment by ManlyMarco** [comment]
It narrows it down a little but yeah, not it's enough. I guess I'll have to take a look at it whenever I get my VR setup back.

If you still want to help debug it, you'll need to grab simple mono profiler from here https://github.com/BepInEx/BepInEx.Debug/releases/tag/r9, extract it into the game, run it, press \` key (backquote, you can change it in plugin settings) once everything is finished loading and you're just chilling in the game, then let it run for a few seconds and press ` again. You should see csv files pop up in the game directory, send me the latest one.

**Comment by FaySmash** [comment]
Here is the CSV

[MonoProfilerOutput_2022-11-15_23-16-33.csv](https://github.com/IllusionMods/KK_Plugins/files/10016560/MonoProfilerOutput_2022-11-15_23-16-33.csv)

**Comment by FaySmash** [comment]
Here you go

[output_log.txt](https://github.com/IllusionMods/KK_Plugins/files/10033814/output_log.txt)

**Comment by ManlyMarco** [comment]
[HS2_MaterialEditor_debug3.zip](https://github.com/IllusionMods/KK_Plugins/files/10034360/HS2_MaterialEditor_debug3.zip)
This should at least partially fix the issue. How bad is the FPS drop compared to the old version now?

**Comment by FaySmash** [comment]
I've got about 16fps with the HS2_MaterialEditor_debug2 and getting ~60-70fps with the HS2_MaterialEditor_debug3, I attached it's log anyways. Seems like the issue got fixed

[output_log.txt](https://github.com/IllusionMods/KK_Plugins/files/10035776/output_log.txt)

**Comment by ManlyMarco** [comment]
Nice, thank you for the help debugging this. You can keep using the debug dll until the new release is finished.
