### ISSUE TITLE
Make shaders source code available for Material Editor

### ISSUE THREAD

**Issue by Grunmatic** [IllusionMods/KK_Plugins#154]
Any chance of getting the .shader files for the shaders in AI_Shaders.unity3d and EC_Shaders.unity3d, for MaterialEditor (specifically for HS2, if it matters).

If not, can we know the reason?

**Comment by DeathWeasel1337** [comment]
Unit's ease of modding comes from the ability to decompile the game code and essentially have access to the source code, but shaders are compiled in a way that can't be decompiled so easily. I have no access to the .shader files for any of these games, copies of the existing compiled shaders are used.

That said, xukmi worked to recreate the vanilla Koikatsu shaders https://github.com/xukmi/KKShadersRecreated and you could probably get them to work for EC if you wanted. I don't know if anyone has worked to recreate the AI or HS2 shaders, sorry. You could try asking the the modding channel of the Illusion Soft Discord.

**Comment by Grunmatic** [comment]
Ah, I thought these were remade/improved versions of the in-game shaders. Thank you for the clarification.
