### ISSUE TITLE
[KKS] issue with ME changes not being loaded

### ISSUE THREAD

**Issue by Ice1965** [IllusionMods/KK_Plugins#156]
I have a couple versions of KK Sunshine, [ScrewthisNioise] R5, and this is not a problem. When I load the game, it loads the ME properties without a problem.  [ScrewThisNoise] version does not have some of the issues that I like. 
I have added the HF-1.7 Update to a copy of the [ScrewThisNoise] version, but when I do, everything works fine except if I edit clothing with ME, those values are saved but they do not load into the game.  I have made changes with Character Editor, as well as editing Appearance in the Booking area. The changes are saved, because if I reload using characters the changes are loaded. When loading a game, and playing the ME changes are not loaded.
Not sure if that describes the problem well enough, I will try to check back in for more clarification or suggestions.
Thank you

**Comment by ElaborateRefrigerator** [comment]
COSPLAY ACADEMY! Try disabing or removing that plugin and see if it fixes it (you can do so through KK Manager). 
I've been having the same issue forever and just now tried disabling Cosplay Academy, which seemed to fix it. I don't have time to test it fully right now, but on first glance, it appeared to be working after I disabled CA.

**Comment by ManlyMarco** [comment]
This issue is reported here https://github.com/jalil49/Cosplay-Academy/issues/5
I think it's an issue entirely on the Cosplay Academy side, so I'll close this one.
