### ISSUE TITLE
[HS2] [Uncensor Selector] HS2_UncensorSelector Base.zipmod is missing

### ISSUE THREAD

**Issue by LightSaveUs** [IllusionMods/KK_Plugins#167]
The RAR archive with UncensorSelector plugin for Honey Select 2 is missing HS2_UncensorSelector Base.zipmod file, which should be located at mods/ folder. Because of this, the plugin does not behave correctly. For example, when you specify a girl futa in HS2 and set the genitals for her, testicles just do not show, although it is listed as selected for her.
I don't know why nobody noticed it before. Probably just human inattention. In general, please put this essential zipmod in the corresponding archive, if you have such a possibility.
P.S. Thank you very much for working on plugins for HS2 and other games from Illusion!

**Comment by ManlyMarco** [comment]
Fixed in latest release.
