### ISSUE TITLE
I'm very new to modding KoikatuSunshine and I ran into a problem with uncensor selector. It listed dependencies that it won't work without and I found all but one, a file referred to as marco.kkapi v1.28. I don't really know what file I'm looking for or where I'd put it so any help would be appreciated.

### ISSUE THREAD

**Issue by chenyu0860025** [IllusionMods/KK_Plugins#170]

**Comment by DeathWeasel1337** [comment]
KKAPI: https://github.com/IllusionMods/IllusionModdingAPI

All of the references are nuget packages that should be automatically downloaded the first time you try to build the project. The first time you open the project, without changing anything, build the solution to download all the references for everything.
![Untitled](https://user-images.githubusercontent.com/37981563/219238983-b8dd60cc-4496-4e90-a91d-1aac9caa491b.png)
