### ISSUE TITLE
[KK] [Material Editor] ME not showing meshes of imported .obj

### ISSUE THREAD

**Issue by RaimeST** [IllusionMods/KK_Plugins#174]
.obj files imported through obj import don't display any meshes/materials past the first one.
Works fine in Material Editor 3.1.19 but any version after that one seems to be bugged (3.1.20-3.1.22)
![objimport_me_issue_A](https://user-images.githubusercontent.com/129168311/229294227-ecc16161-47cb-41bd-9039-bc4a3ad9c7df.png)
![objimport_me_issue_B](https://user-images.githubusercontent.com/129168311/229294240-3ca1825a-ae3f-4310-b802-07cb77763b68.png)

**Comment by ManlyMarco** [comment]
Does this still happen in the latest version?

**Comment by RaimeST** [comment]
Nope, all fixed now. Thanks!
