### ISSUE TITLE
ME Keywords

### ISSUE THREAD

**Issue by Hanmen-lab** [IllusionMods/KK_Plugins#177]
Could you help me to implement a feature in ME? I want to make the ability to control keywords. Currently ME cannot set the keywords value even if it's property been changed.
And this essential for my work because the shader branching not working. Basically, I need the function `material.SetKeyword` on the respective property. Currently all new keywords on the replaced shader are 0 because the original material don't have it and the current function cannot set the keyword state correctly. 

This for reference:

https://docs.unity3d.com/ScriptReference/Material.SetKeyword.html
https://docs.unity3d.com/ScriptReference/Rendering.LocalKeyword.html

**Comment by BullOnMars** [comment]
This can be marked as closed now.
