### ISSUE TITLE
[HS2] (AccessoriesToStudioItems ) Can't the find accessories

### ISSUE THREAD

**Issue by rgshinob** [IllusionMods/KK_Plugins#206]
![Screenshot (97)](https://github.com/IllusionMods/KK_Plugins/assets/68125480/eb3ebb8f-caf3-43b2-9316-d5ce277e74c9)
i cant find accessories as in my screenshot
i've also already update the requirement plugin

![Screenshot (96)](https://github.com/IllusionMods/KK_Plugins/assets/68125480/7cc8b93e-b853-4ea4-afd5-f146a6bafae9)
![Screenshot (95)](https://github.com/IllusionMods/KK_Plugins/assets/68125480/ee3f54f4-04b7-451b-b45e-67fb379fc7f8)
is there something i did wrong
thanks

**Comment by ManlyMarco** [comment]
99.9% you didn't update other required plugins.
