### ISSUE TITLE
[KK] (AccessoriesToStudioItems) Skinned Accessories Remain Stuck Across All Scenes, Requiring Restart

### ISSUE THREAD

**Issue by RecklessJames** [IllusionMods/KK_Plugins#211]
Decided to update today and try out this new plugin, which is a fantastic addition to everything btw!

But then realized that many of the skinned Accessories are now going to be junking up the search engine... which was a minor annoyance at first, but then this minor annoyance is suddenly an actual bigger problem once I realized that if you load any of these type of accessories (very often will be by mistake too imho) they remain in all scenes and cannot be removed unless you restart all of Studio. I restarted Studio to test this more than one time, and sadly this happens every single time.

![CharaStudio-2023-12-15-22-40-22-UI](https://github.com/IllusionMods/KK_Plugins/assets/12752293/8918c555-34a8-4f64-97d1-c9f5418d8bfa)

This happened to me after I was loading just random stuff to test how this worked, and then when I reset the scene I noticed that "static" items were still there. So I loaded another scene and yup sure enough... still remains. Not listed within the workplace window either.

One mistake/misclick and boom, now you gotta restart studio. Certainly also cannot be resolved by simply "not clicking on them" as not every item is clear on if its a skinned accessory or not. In addition to hopefully bringing attention to this, I'd like to also suggest that maybe these type of items shouldn't even be listed at all to begin with? If that's even possible, which probably not, but at least worth mentioning the idea since we're talking 100s of these type of items that will be in the studio search engine from now on. Or perhaps a new filter type listed for CharaMaker accessories.

**Comment by BullOnMars** [comment]
He probably means skinned accessories.

**Comment by RecklessJames** [comment]
> He probably means skinned accessories.

Wasnt sure the exact term, but yes correct.

**Comment by RecklessJames** [comment]
I am now learning that this does not happen to others except for me, and absolutely zero idea why.
