### ISSUE TITLE
AI Shoujo uncensor (apologies if this is posted in the wrong place)

### ISSUE THREAD

**Issue by Razor2568** [IllusionMods/KK_Plugins#212]
Hi,

First off I'd like to just say again apologies if this is posted in the wrong place and I'm sorry if this has been asked and closed before but not sure what else to do now, so here goes.

I have the Steam version of AI Shoujo and HS2 (both purchased through Steam Store I want to add) and have installed the latest HF patches from ManlyMarco on Patreon installed on both. As I don't want to take up too much of anyone's time, I'm just looking for quick answer to something I've been trying to figure out for days now.

Does the 'balls option' for a female character in AI Shoujo work?

Everything works fine in HS2 and I've done a lot of digging/messing about before posting this including using KKmanager to disable any plugins and zipmods not need by 'UncensorSelector to work just incase they were messing with it somehow. When I check the 'futanari' box in AI's character maker the penis shows up and works correctly and I have the dropdown menu for balls with options in it but when selecting one, nothing is visible/shows up on the character's body. Typing 'dan' into the dynamic bones menu shows they are loaded and clicking an option even brings up the blue, green and red XYZ axis where the balls are supposed to be and the balls I'm trying to use are loading in game because they show up on male characters and also on female characters in AI's version of studio, just not the main game and game character maker. Again everything is fine in HS2. I've actually even tried 'breaking' HS2 to try and get it to potentially show me what might be AI Shoujo's issue and the only way I could get the balls to not show in HS2 was turn off UncensorSelector. Sorry for the huge story but I've tried all sorts, more than I write could here, but...

Do balls show up on female characters in AI Shoujo (Steam plus HF patch) or are they intentionally disabled?

And sorry if I'm now asking the wrong person/people if these mods are no longer being developed/worked on.

Thanks in advance for any help I receive.

**Comment by ManlyMarco** [comment]
The feature is partially broken in AI. It works correctly in studio and I think in the jp release. Currently no one is interested in fixing it.

**Comment by Razor2568** [comment]
Ok, thanks for the reply. No problem, its understandable if there isn't any interest, especially if no one plays AI main game (at least the Steam version anyway). Sounds like it would be a bit of a headache to fix.

Once again, I appreciate the response, both here and your own page. I'll close the case.
