### ISSUE TITLE
[KKS] [Material Editor] Feature Request - Include Lux Water Shader In Manifest

### ISSUE THREAD

**Issue by krypto5863** [IllusionMods/KK_Plugins#214]
Lux Water is an incredibly cool little water shader I've messed with through Unity Runtime Inspector to make some really cool scenes in Studio. But it's not as comfortable as just dropping the umi item and tweaking it with Material Editor.

Here's a little more on how the shader works: https://docs.google.com/document/d/1NDtUpVBgd3UYEI8LRNI4teFF3qm38h-u3Az-ozaaOX0/mobilebasic

So I'm just hoping that the shader and all it's properties are properly defined so we can control it fully in Material Editor.

Thanks!

**Comment by ManlyMarco** [comment]
It seems like it would work better as a shader zipmod.

**Comment by krypto5863** [comment]
Yeah, fair enough.
