### ISSUE TITLE
[KK] [Material Editor] Unreferenced textures are not purged in Studio

### ISSUE THREAD

**Issue by MakaoPoo** [IllusionMods/KK_Plugins#223]
When saving a scene, unreferenced texture data is not deleted.
This has been happening since timeline support was added.

The cause can be attributed to `SceneController.OnSceneSave` in `Core.MaterialEditor.SceneController.cs`.
Lines 49-51.
`foreach (int texID in TextureDictionary.Keys)`
`  if (MaterialTexturePropertyList.All(x => x.TexID != texID && ExternallyReferencedTextureIDs.Contains(texID)))`
`    IDsToPurge.Add(texID);`

I think the correct code is this.
`foreach (int texID in TextureDictionary.Keys)`
`  if (MaterialTexturePropertyList.All(x => x.TexID != texID && !ExternallyReferencedTextureIDs.Contains(texID)))`
`    IDsToPurge.Add(texID);`

Sorry if this is poorly written.
Thanks again for all the great plugins you provide.
(DeepL: JPN→ENG)

**Comment by takahiro0327** [comment]
Hello. Thanks for presenting the buggy code.
I've fixed it and you can try it.
[KK_MaterialEditor.zip](https://github.com/IllusionMods/KK_Plugins/files/14138700/KK_MaterialEditor.zip)


差し出がましいですが、そこまで特定できていたならPR作って問題なかったかと思います。

**Comment by MakaoPoo** [comment]
Thanks for the fix.
It worked fine.

Issueを投稿するのは初めてだったため、お手数おかけしました。
迅速な対応、ありがとうございます！
