### ISSUE TITLE
[KK][Materialeditor] When texture was no longer used, it seems not going to be deleted unless all modified textures was reset

### ISSUE THREAD

**Issue by mrxuzhen** [IllusionMods/KK_Plugins#242]
when I am tring to clean the maintex to cut down the size of scene data, I found something stange. When there have mutiple image plate or fake shader(or item shader, whatever you call it) whose maintex was imported, I can't simply reset the maintex to cut down size of scene data, even after I save the scene data many times, the size of data won't change a little. I must reset all the maintex,detailmask,normalmap in material editor. Only after all the tex was reset, the size of data will be cut down. That is really annoying because I am pretty sensitive to the size of data.
I personally guess that it is because material editor fails to figure out how many items are using a same texture. As a scene maker I usually use "copy paste" function to copy texture and shaders to another item, it causes reuse of texture to cut down size of scenedata. But now it seems that material editor can't figure out which texture was no longer used and delete it, that is pretty annoying
I don't know when and how this problem begins, I also have no idea is it the problem of materialeditor or not. Anyway, here it is.

**Comment by takahiro0327** [comment]
I think this is a bug that was fixed in the following PR.

https://github.com/IllusionMods/KK_Plugins/issues/223
https://github.com/IllusionMods/KK_Plugins/pull/224/files
