### ISSUE TITLE
How do you disable ClothingUnlocker?

### ISSUE THREAD

**Issue by RedEyedRocker** [IllusionMods/KK_Plugins#89]
I've tried the toggle option in the plugin settings but nothing happens.

I've even disabled the plugin itself via KKManager but for some reason the gender restricted clothing is still unlocked.

**Comment by DeathWeasel1337** [comment]
You can disable the plugin in plugin settings or by removing the .dll. Some clothes may show up for either gender anyway depending on how the modder configured them.

**Comment by RedEyedRocker** [comment]
> 
> 
> Some clothes may show up for either gender anyway depending on how the modder configured them.

The issue is that all clothes(not just modded) are showing up for both genders regardless of removing the .dll file.

**Comment by DeathWeasel1337** [comment]
Do you have a second copy of the .dll somewhere in your plugins folder? Not really sure what could cause this. Try removing plugins a bunch at a time and see if you can narrow down the cause.

**Comment by RedEyedRocker** [comment]
> 
> 
> Do you have a second copy of the .dll somewhere in your plugins folder? Not really sure what could cause this. Try removing plugins a bunch at a time and see if you can narrow down the cause.

I don't find any duplicates in the plugins folder, it's both disabled in its config and KKManager.

These are all the mods I have:
![Screenshot 01](https://i.imgur.com/XNvjgYw.png)
![Screenshot 02](https://i.imgur.com/6rEvapU.png)
![Screenshot 03](https://i.imgur.com/5MMpBdD.png)
![Screenshot 04](https://i.imgur.com/XdEkpbC.png)
