### ISSUE TITLE
[HS2] Uncensor Selector Should not override per person if the default body is not selected

### ISSUE THREAD

**Issue by YuliaS11** [IllusionMods/KK_Plugins#92]
Make it so if a character is not using the default censored selection, then don't override it at all. This is quiet annoying in many instances.

**Comment by ManlyMarco** [comment]
Can you explain what exactly you mean by default censored selection and override?

**Comment by YuliaS11** [comment]
So if say I have an uncensor that is not the default option selected, then I would get that instead of being automatically assigned by the uncensor. More over, please consider unlocking the two male slots for female even if not flagged as Futanari.

**Comment by ManlyMarco** [comment]
Closing stale issue, if anyone can reproduce the issue on latest release please reopen.
