### ISSUE TITLE
KKS_MoreOutfits Iris Issue

### ISSUE THREAD

**Issue by ASwanderer** [IllusionMods/KK_Plugins#96]
Accessories and Clothes load fine, including the extra outfits: Outfit 5, Outfit 6, Outfit 7. However, the additional 3 Coordinates that are added seem to default to a specific type of Iris(Type AM for me). Attempts to change the iris results in a game crash after a few seconds. Latest version of the BepisPlugins and IllusionModdingAPI are installed, and this plugin is new, so issues were to be expected. It could also just be me doing something wrong here.

**Comment by ASwanderer** [comment]
It seems that it defaults to that only if the Iris the character is using is from a mod. If the Iris is from the base game, it doesn't change to something else, but trying to change it also crashes the game, but that could be an issue from another plugin.

**Comment by ASwanderer** [comment]
The crash is most likely from the amount of mods there are. This plugin has nothing to do with it.

**Comment by DeathWeasel1337** [comment]
I found Sunshine was crashing due to two iris mods, I fixed them and you should be able to get the fixed version by updating with KKManager, or you can remove these two mods:
[Anon] Black Bullet Enju
[Anon] Black Bullet Kohina

**Comment by ASwanderer** [comment]
The update fixed the crashing issue. Also, it seems that it wasn't the iris type not loading correctly but is instead the Iris Overlay not getting ported to Outfits 5,6,7, while it does get ported to the 4 Coordinates the game provides. It's an easy fix since we can export the overlay and apply it on the outfits, but it becomes a hassle when there's too many characters with that issue.

**Comment by DeathWeasel1337** [comment]
Glad to hear it fixed the crashing. I tried iris overlays and they seem to import correctly. Make sure you have the latest version of the Overlay plugin and try importing the character again, if you imported it on an old version it may not have imported properly.
