### ISSUE TITLE
Requesting Feature for Uncensor Selector

### ISSUE THREAD

**Issue by ThatDude79** [IllusionMods/KK_Plugins#97]
Requesting the ability for Material Editor changes to the body be retained when switching uncensors in Maker.

For example, if the body was set to a specific shader, and you changed the uncensor, would it be possible for the plugin to copy the changes made to the current body's materials, before switching uncensors, then reapplying those changes?

ps: I haven't used github before, so if I'm going about this request incorrectly, I'm sorry.

**Comment by DeathWeasel1337** [comment]
That's a good suggestion, it's something I've been meaning to do but always forget. I implemented this and released the updates:
https://github.com/IllusionMods/KK_Plugins/releases/tag/v204
